# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Roberto Pedroso
description:      'University of Chicago graduate with a degree in <a href="http://philosophy.uchicago.edu/">nerdiness</a>. A hacker and geek who lives appsec, arguments about AI and <a href="http://minecraft.net" target="_blank">playing games</a>.'
url:              http://rpedroso.com

# Use Github markdown
kramdown:
  input:          GFM

author:
  name:           'Roberto Pedroso'
  email:          roberto@rpedroso.com
  url:            https://rpedroso.com

paginate:         5

github:
  repo:           https://github.com/robertopedroso/robertopedroso.github.com

so:
  prof:		      https://stackoverflow.com/users/673904/rpedroso
