# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Roberto Pedroso
description:      'A hacker, geek and philosopher who likes appsec, <a href="http://minecraft.net" target="_blank">playing games</a> and reading <a href="http://www.amazon.com/After-Virtue-Study-Theory-Edition/dp/0268035040" target="_blank">books</a>.'
url:              http://rpedroso.com

# Use Github markdown
kramdown:
    input: GFM

author:
  name:           'Roberto Pedroso'
  email:          roberto@rpedroso.com
  url:            https://rpedroso.com

paginate:         5

github:
  repo:           https://github.com/robertopedroso/robertopedroso.github.com

so:
  prof:		      https://stackoverflow.com/users/673904/rpedroso
